#Turtle 모듈
import turtle


#구각형 그리기
turtle.shape("turtle")
turtle.color("purple")
turtle.begin_fill()
turtle.forward(150)
turtle.left(40)
turtle.forward(150)
turtle.left(40)
turtle.forward(150)
turtle.left(40)
turtle.forward(150)
turtle.left(40)
turtle.forward(150)
turtle.left(40)
turtle.forward(150)
turtle.left(40)
turtle.forward(150)
turtle.left(40)
turtle.forward(150)
turtle.left(40)
turtle.forward(150)
turtle.left(40)
turtle.end_fill()

#팔각형 그리기
turtle.shape("turtle")
turtle.color("pink")
turtle.begin_fill()
turtle.forward(150)
turtle.left(45)
turtle.forward(150)
turtle.left(45)
turtle.forward(150)
turtle.left(45)
turtle.forward(150)
turtle.left(45)
turtle.forward(150)
turtle.left(45)
turtle.forward(150)
turtle.left(45)
turtle.forward(150)
turtle.left(45)
turtle.forward(150)
turtle.left(45)
turtle.end_fill()

#육각형 그리기
turtle.shape("turtle")
turtle.color("green")
turtle.begin_fill()
turtle.forward(150)
turtle.left(60)
turtle.forward(150)
turtle.left(60)
turtle.forward(150)
turtle.left(60)
turtle.forward(150)
turtle.left(60)
turtle.forward(150)
turtle.left(60)
turtle.forward(150)
turtle.left(60)
turtle.end_fill()

#오각형 그리기
turtle.shape("turtle")
turtle.color("yellow")
turtle.begin_fill()
turtle.forward(150)
turtle.left(72)
turtle.forward(150)
turtle.left(72)
turtle.forward(150)
turtle.left(72)
turtle.forward(150)
turtle.left(72)
turtle.forward(150)
turtle.left(72)
turtle.end_fill()

#사각형 그리기
turtle.shape("turtle")
turtle.color("orange")
turtle.begin_fill()
turtle.forward(150)
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.end_fill()

#삼각형 그리기
turtle.shape("turtle")
turtle.color("red")
turtle.begin_fill()
turtle.forward(150)
turtle.left(120)
turtle.forward(150)
turtle.left(120)
turtle.forward(150)
turtle.left(120)
turtle.end_fill()
